# Model parameters
n_estimators: 100
max_depth: 10
random_state: 42

# MLflow settings
mlflow:
  tracking_uri: "file:./mlruns"  # or http://your-mlflow-server:5000
  experiment_name: "kedro-experiment"
